workspace(name = "grafonnet")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_jsonnet",
    sha256 = "7f51f859035cd98bcf4f70dedaeaca47fe9fbae6b199882c516d67df416505da",
    strip_prefix = "rules_jsonnet-0.3.0",
    urls = ["https://github.com/bazelbuild/rules_jsonnet/archive/0.3.0.tar.gz"],
)

load("@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_repositories")

jsonnet_repositories()

load("@jsonnet_go//bazel:repositories.bzl", "jsonnet_go_repositories")

jsonnet_go_repositories()

load("@jsonnet_go//bazel:deps.bzl", "jsonnet_go_dependencies")

jsonnet_go_dependencies()

http_archive(
    name = "com_github_grafana_grafonnet-lib",
    build_file_content = """
load(
    "@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl",
    "jsonnet_library",
)

jsonnet_library(
    name = "grafonnet",
    srcs = glob(["grafonnet/*"]),
    visibility = ["//visibility:public"],
)
""",
    sha256 = "571ff5e6a44b583b8069476fb720f70a97a39734d206eae41c1c4f12af0a05d1",
    strip_prefix = "grafonnet-lib-0.1.0",
    urls = [
        "https://github.com/grafana/grafonnet-lib/archive/v0.1.0.zip",
    ],
)
